import api from './auth.js'

export const listTargets        = (params = {}) => api.get('/supply/targets', { params })
export const createTarget       = (data)         => api.post('/supply/targets', data)
export const updateTarget       = (id, data)     => api.put(`/supply/targets/${id}`, data)
export const deleteTarget       = (id)           => api.delete(`/supply/targets/${id}`)
export const getReplenishment   = (params = {})  => api.get('/supply/replenishment', { params })
export const createReposition   = (data)         => api.post('/supply/reposition', data)
export const suggestSource           = (params = {})      => api.get('/supply/suggest-source', { params })
export const getProductSuppliers     = (productId)        => api.get(`/supply/product-suppliers/${productId}`)
export const addProductSupplier      = (productId, data)  => api.post(`/supply/product-suppliers/${productId}`, data)
export const updateProductSupplier   = (productId, supplierId, data) => api.put(`/supply/product-suppliers/${productId}/${supplierId}`, data)
export const removeProductSupplier   = (productId, supplierId)       => api.delete(`/supply/product-suppliers/${productId}/${supplierId}`)
export const createPurchaseRequisition = (data)           => api.post('/supply/purchase-requisition', data)
export const listTransitLanes   = ()            => api.get('/supply/transit-lanes')
export const createTransitLane  = (data)        => api.post('/supply/transit-lanes', data)
export const updateTransitLane  = (id, data)    => api.put(`/supply/transit-lanes/${id}`, data)
export const deleteTransitLane  = (id)          => api.delete(`/supply/transit-lanes/${id}`)
export const getPurchasePrediction = (params = {}) => api.get('/supply/purchase-prediction', { params })
